clc;
clear;

% Загружаем данные
load("results.mat");

% Создаем окно Figure
fig = figure('Name', 'Практическая работа 2', ...
    'NumberTitle', 'off', ...
    'Position', [100, 100, 1000, 800]);

% Функция для красивого вывода матриц
function formatted_matrix = format_matrix(M)
    [rows, cols] = size(M);
    formatted_matrix = "";
    for i = 1:rows
        row_str = "| ";
        for j = 1:cols
            row_str = strcat(row_str, sprintf("%6.2f ", M(i, j))); % Выравниваем до 2 знаков
        end
        row_str = strcat(row_str, "|\n");
        formatted_matrix = strcat(formatted_matrix, row_str);
    end
end

% Вычисляем β и α
beta = inv(A(:, 1:rank(A))) * B;
alpha = inv(A(:, 1:rank(A))) * A(:, rank(A)+1:end);

% Формируем уравнение в базисных переменных
equation_str = "   xБ = [ ";
for i = 1:length(beta)
    equation_str = strcat(equation_str, sprintf("%.3f ", beta(i)));
end
equation_str = strcat(equation_str, "] + [ ");

for i = 1:size(alpha, 1)
    equation_str = strcat(equation_str, sprintf("%.3f ", alpha(i, :)));
    if i < size(alpha, 1)
        equation_str = strcat(equation_str, "; ");
    end
end
equation_str = strcat(equation_str, "] * xH");

% Формируем текст с результатами
report_text = sprintf([
    "Практическая работа 2\n\n" ...
    "Вариант: 10\n" ...
    "Группа: 3\n" ...
    "ФИО: Коломиец Александр, Морозов Михаил\n\n" ...
    "1. Выписаны исходные данные:\n" ...
    "   Целевая функция: max(11x1 + 18x2 + 7x3 + 13x4 + x5 + 14x6 + 5x7)\n\n" ...
    "   Ограничения A:\n" ...
    format_matrix(A) "\n" ...
    "   Вектор B:\n" ...
    format_matrix(B) "\n\n" ...
    "2. Матрица ограничений A записана.\n\n" ...
    "3. Вектор B записан.\n\n" ...
    "4. Ограничения приведены к уравнениям:\n" ...
    format_matrix(A) "\n\n" ...
    sprintf("5. Определен ранг базисных переменных: m = %d\n\n", rank(A)) ...
    "6. Определены матрицы D и S:\n" ...
    "D =\n" format_matrix(A(:, 1:rank(A))) "\n" ...
    "S =\n" format_matrix(A(:, rank(A)+1:end)) "\n\n" ...
    "7. Найдена обратная матрица D⁻¹:\n" ...
    format_matrix(inv(A(:, 1:rank(A)))) "\n\n" ...
    "8. Вычислены коэффициенты βi:\n" ...
    format_matrix(beta) "\n\n" ...
    "9. Вычислены коэффициенты αij:\n" ...
    format_matrix(alpha) "\n\n" ...
    "10. Записано уравнение в базисных переменных.\n" ...
    equation_str "\n\n" ...
    "Выводы не включены. Их нужно будет сформулировать самостоятельно.\n"
]);

% Отображаем текстовое поле с результатами (прокрутка включена)
uicontrol('Style', 'edit', ...
    'String', report_text, ...
    'Position', [20, 50, 960, 700], ...
    'FontSize', 12, ...
    'HorizontalAlignment', 'left', ...
    'Max', 10, 'Min', 0, ...
    'Enable', 'inactive');

% Ожидание закрытия окна пользователем
waitfor(fig);